[dev]
  command = "yarn start"
  port = 3000
  publish = "dist"

[build]
  command = "yarn run bootstrap && yarn run create-indexes && yarn build"
  publish = "build/"
  functions = 'build/functions'
